language: ruby
bundler_args: '--without development exclude_travis'
cache: bundler
dist: trusty
rvm:
  - 2.3.4
matrix:
  fast_finish: true
script:
  - bundle exec rubocop -c .rubocop.yml --fail-level C
  - bundle exec rspec
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
sudo: false
